### ISSUE TITLE
Crash when player kill mobs

### ISSUE THREAD

**Issue by Daudeuf** [MinestrapTeam/Minestrappolation-5#3]
[11:42:14] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block minestrapp:skull_enderman, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.withProperty(BlockStateContainer.java:227) ~[awu$a.class:?]
	at minestrapp.block.BlockMSkull.getStateFromMeta(BlockMSkull.java:170) ~[BlockMSkull.class:?]
	at mods.railcraft.common.util.inventory.InvTools.getBlockStateFromStack(InvTools.java:488) ~[InvTools.class:?]
	at mods.railcraft.common.blocks.tracks.TrackTools.isRailBlock(TrackTools.java:73) ~[TrackTools.class:?]
	at mods.railcraft.common.advancements.criterion.TrackItemPredicate.test(TrackItemPredicate.java:66) ~[TrackItemPredicate.class:?]
	at net.minecraft.advancements.critereon.InventoryChangeTrigger$Instance.test(SourceFile:104) ~[al$b.class:?]
	at net.minecraft.advancements.critereon.InventoryChangeTrigger$Listeners.trigger(SourceFile:149) ~[al$a.class:?]
	at net.minecraft.advancements.critereon.InventoryChangeTrigger.trigger(SourceFile:69) ~[al.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.sendSlotContents(EntityPlayerMP.java:972) ~[oq.class:?]
	at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:91) ~[afr.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdate(EntityPlayerMP.java:324) ~[oq.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1955) ~[amu.class:?]
	at net.minecraft.world.WorldServer.tickPlayers(WorldServer.java:642) ~[oo.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1734) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more

**Comment by Delocuro** [comment]
Wrong repository, lol -- this one's been defunct for a long while. Thanks for actually reporting the crash, though! The active repository can be found here: https://github.com/MinestrapTeam/Minestrapp-1.12/issues

This is a known issue, but it's not really a Minestrapp problem -- it's actually a bug with the item physics mod or whatever it's called. Apparently it tries to get facing states from any block that can be directionally placed, but doesn't check whether the block has states for all 6 facing directions, which can cause crashes any time a modded block without all 6 facing states is dropped on the ground. Supposedly the mod devs have been alerted to the issue and intend to fix it -- you may want to try updating that mod and see if that solves it, otherwise you may need to remove it until they get the issue fixed.
